# Generated by Django 5.0.7 on 2024-08-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='bidder_id',
            field=models.IntegerField(default=970777119, unique=True),
        ),
    ]
