# Generated by Django 5.0.7 on 2024-08-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0002_itemimages_auctionitem_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidder",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
