# Generated by Django 5.0.7 on 2024-08-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_bidder_bidder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='bidder_id',
            field=models.IntegerField(default=559375610, unique=True),
        ),
    ]
