# Generated by Django 5.0.7 on 2024-08-15 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_bidder_stripe_id_alter_auctionitem_auction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='payment_intent_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
