# Generated by Django 5.0.7 on 2024-08-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_remove_bidder_bidder_id_auctionitem_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='value',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
