# Generated by Django 5.0.7 on 2024-08-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_bidder_stripe_id_alter_auctionitem_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='bidder_id',
            field=models.CharField(max_length=9, unique=True, blank=True, null=True),
        ),
    ]
