# Generated by Django 5.0.7 on 2024-08-09 01:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_alter_bidder_bidder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='stripe_id',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
