# Generated by Django 5.0.7 on 2024-08-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0008_bidder_stripe_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidder",
            name="bidder_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
