# Generated by Django 5.0.7 on 2024-08-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_bidder_bidder_id_bidder_stripe_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='auctionitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-amount']},
        ),
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
