# Generated by Django 5.0.7 on 2024-08-18 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_bid_setup_intent_id_bidder_stripe_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='runner_up',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_up', to='auction.bidder'),
        ),
    ]
